#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

if [ "$FILES" != "" ]
then
    echo "\n\nChecking PHP Lint..."
    for FILE in $SFILES
    do
        php -l -d display_errors=0 $PROJECT/$FILE
        if [ $? != 0 ]
        then
            echo "Fix the error before commit."
            exit 1
        fi
        FILES="$FILES $PROJECT/$FILE"
    done
fi

if [ "$FILES" != "" ]
then
	echo "\n\nRunning Code Sniffer..."
	vendor/bin/phpcs --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml --encoding=utf-8 --colors -n -p $FILES
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
fi


echo "\n\nRunning tests..."
vendor/bin/tester tests -s -c tests/php-unix.ini
if [ $? != 0 ]
then
    echo "Fix the error before commit."
    exit 1
fi

exit $?